sudo: false

language: node_js

branches:
  only:
    - master

env:
  - CXX=g++-4.8

node_js:
  - "6.5"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - build-essential

matrix:
  include:
    - env: BUILD=1
      sudo: required
      services: [docker]

before_script:
  - if [ -z "$BUILD" ]; then npm install; fi

script:
  - if [ -z "$BUILD" ]; then npm run lint; fi
  - if [ -z "$BUILD" ]; then npm run test; fi
  - if [ -z "$BUILD" ]; then npm run coverage; fi
  - if [ ! -z "$BUILD" ]; then docker run -v $(pwd):/cwd snapcore/snapcraft sh -c 'cd /cwd && apt update && apt install -y snapcraft && snapcraft'; fi
