sudo: false

language: node_js

branches:
  only:
    - master

env:
  - CXX=g++-4.8

node_js:
  - "6.5"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - build-essential

before_script:
  - npm install

script:
  - npm run lint
  - npm run test
  - NODE_ENV='test' node ./node_modules/nyc/bin/nyc.js ./node_modules/mocha/bin/_mocha --require babel-register && node ./node_modules/nyc/bin/nyc.js report --require babel-register --reporter=lcov && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
