# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- azure-pipelines


jobs:
  - job: test_ui
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 10.15
      - script: |
          yarn lint && yarn test
          # This is here to confirm the build works.
          # Nothing is done with the resulting artifacts.
          yarn build --dev
        displayName: 'lint and test'
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'junit.xml'

  - job: deploy_ui
    dependsOn:
      - test_ui
    strategy:
      maxParallel: 10
      matrix:
        dev:
          COMMAND: run docker:release -- dev
        sneakpeak:
          COMMAND: run docker:release -- sneakpeak
        kovan:
          COMMAND: run docker:release -- kovan
        dev-optimized:
          COMMAND: run docker:release -- dev-optimized

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 10.15
      - task: Docker@1
        displayName: docker login
        inputs:
          command: login
          containerRegistryType: Container Registry
          dockerRegistryEndpoint: dockerhub-augurproject
      - task: Npm@1
        inputs:
          command: custom
          customCommand: $(COMMAND)
      condition: |
        and
        (
            succeeded(),
            eq(variables['Build.SourceBranch'], 'refs/heads/master')
        )

